CREATE TABLE comment (
    id INT NOT NULL AUTO_INCREMENT,
    post_id INT NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    avatar VARCHAR(50) NOT NULL,
    body TEXT NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE
);